# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-symlinks
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.9
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff-check
        args: [--config, tools/ruff.toml]
      - id: ruff-format
        args: [--config, tools/ruff.toml]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [--config, tools/.codespellrc]
  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint-docker
        args: [--config, tools/.hadolint.yaml]
  - repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-jinja
        args: [--configuration, tools/djlintrc]
      - id: djlint-jinja
        args: [--configuration, tools/djlintrc]
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 43.47.0
    hooks:
      - id: renovate-config-validator
  - repo: https://github.com/PyCQA/doc8
    rev: v2.0.0
    hooks:
      - id: doc8
        args: [--config, tools/doc8.ini]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.21.0
    hooks:
      - id: markdownlint-cli2
        args: [--config, tools/.markdownlint.yml]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/timo-reymann/gitlab-ci-verify
    rev: v2.10.0
    hooks:
      - id: gitlab-ci-verify
        args: [--severity, warning]
