services:
  cata-log:
    image: cata-log:latest
    container_name: cata-log
    volumes:
      - /path/to/cata-log/storage:/mnt/storage
      - /path/to/cata-log/db:/mnt/db
      - /path/to/cata-log/log:/var/log/cata-log
      - /path/to/cata-log/plugins:/mnt/plugins
    ports:
      - 2424:2424
    environment:
      - PASSWORD=test1234 # gitleaks:allow
      - LOG_LEVEL=DEBUG
      - DEBUG=True
    restart: unless-stopped
