services:
  cata-log:
    image: dacid99/cata-log:latest
    container_name: cata-log
    volumes:
      - /path/to/cata-log/storage:/mnt/storage
      - /path/to/cata-log/db:/mnt/db
      - /path/to/cata-log/log:/var/log/cata-log
      - /path/to/cata-log/plugins:/mnt/plugins
    ports:
      - 2424:2424
    environment:
      - CATA_LOG_USERNAME=admin
      - CATA_LOG_PASSWORD=SafE_pAs5w0rd # setting no password makes authentication impossible #gitleaks:allow
      - CATA_LOG_PUBLIC_GET= # set this to make all GET endpoints unprotected
      - CATA_LOG_REQUEST_TIMEOUT=10
      - CATA_LOG_MAX_RETRIES=3
      - CATA_LOG_RETRY_DELAY=180
      - CATA_LOG_EXPIRATION_DAYS=14
      - CATA_LOG_LOG_LEVEL=INFO
      - CATA_LOG_LOG_FILE_BACKUP_COUNT=10
      - CATA_LOG_LOG_FILE_MAXSIZE=2097152
      - CATA_LOG_DEBUG= # set this for debug mode
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
