fix_and_format_codebase:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
  allow_failure: true
  script:
    - uv pip install --with lint
    - echo "Checking for fixes and formatting ..."
    - mkdir -p "$CHECK_REPORT_PATH"
    - uv run ruff format --config="$CHECK_CONFIG_PATH"ruff.toml --show-fixes | tee "$CHECK_REPORT_PATH"ruff_format.ansi || true
    - uv run djlint src/ --check --configuration "$CHECK_CONFIG_PATH"djlintrc | tee "$CHECK_REPORT_PATH"djlint_format.ansi || true
    - uv run codespell --summary --config="$CHECK_CONFIG_PATH".codespellrc src/ test/ docs/ .gitea/ .github/ .gitlab/ ./*.md | tee "$CHECK_REPORT_PATH"codespell_check.ansi || true
    - uv run doc8 --config "$CHECK_CONFIG_PATH"doc8.ini docs/ | tee "$CHECK_REPORT_PATH"doc8_check.ansi || true
    - echo "Successfully checked codebase for fixes and formatting."
  artifacts:
    paths:
      - "$CHECK_REPORT_PATH"
    when: always
    expire_in: 30 days
